#!/bin/bash
# Cleanup Script Template - REVIEW BEFORE EXECUTING
# Generated from file analysis

set -e  # Exit on any error

# BACKUP FIRST (UNCOMMENT TO ENABLE)
# tar -czf project_backup_$(date +%Y%m%d_%H%M%S).tar.gz .

echo 'Starting cleanup...'

# GENERATED FILES (Safe to delete)
echo 'Cleaning generated files...'
# rm -rf 'results/figures/completion_time_distribution.png'  # Generated file pattern
# rm -rf 'jekyll_site/build.sh'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip-25.1.1.dist-info/RECORD'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip-25.1.1.dist-info/WHEEL'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip-25.1.1.dist-info/entry_points.txt'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip-25.1.1.dist-info/top_level.txt'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip-25.1.1.dist-info/REQUESTED'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip-25.1.1.dist-info/INSTALLER'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip-25.1.1.dist-info/METADATA'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip-25.1.1.dist-info/licenses/LICENSE.txt'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip-25.1.1.dist-info/licenses/AUTHORS.txt'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/wheel_builder.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/build_env.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/network/__pycache__/session.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/network/__pycache__/download.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/network/__pycache__/xmlrpc.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/network/__pycache__/utils.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/network/__pycache__/cache.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/network/__pycache__/lazy_wheel.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/network/__pycache__/auth.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/network/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/setuptools_build.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/temp_dir.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/_jaraco_text.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/glibc.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/urls.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/setuptools_build.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/unpacking.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/packaging.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/logging.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/appdirs.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/compat.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/deprecation.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/filetypes.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/misc.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/filesystem.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/wheel.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/compatibility_tags.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/hashes.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/direct_url_helpers.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/datetime.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/egg_link.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/entrypoints.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/virtualenv.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/_log.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/retry.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/utils/__pycache__/subprocess.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/models/__pycache__/target_python.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/models/__pycache__/link.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/models/__pycache__/candidate.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/models/__pycache__/pylock.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/models/__pycache__/wheel.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/models/__pycache__/selection_prefs.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/models/__pycache__/installation_report.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/models/__pycache__/format_control.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/models/__pycache__/search_scope.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/models/__pycache__/scheme.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/models/__pycache__/index.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/models/__pycache__/direct_url.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/models/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/__pycache__/build_env.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/__pycache__/main.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/__pycache__/pyproject.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/__pycache__/self_outdated_check.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/__pycache__/exceptions.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/__pycache__/cache.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/__pycache__/configuration.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/__pycache__/wheel_builder.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/cli/__pycache__/main.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/cli/__pycache__/req_command.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/cli/__pycache__/autocompletion.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/cli/__pycache__/cmdoptions.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/cli/__pycache__/base_command.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/cli/__pycache__/main_parser.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/cli/__pycache__/status_codes.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/cli/__pycache__/progress_bars.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/cli/__pycache__/command_context.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/cli/__pycache__/index_command.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/cli/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/cli/__pycache__/spinners.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/cli/__pycache__/parser.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/install/__pycache__/wheel.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/install/__pycache__/editable_legacy.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/install/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/__pycache__/check.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/__pycache__/freeze.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/__pycache__/prepare.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/wheel_legacy.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/metadata.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/metadata_editable.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/wheel_editable.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/__init__.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/metadata_legacy.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/wheel.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/build_tracker.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/__pycache__/wheel_legacy.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/__pycache__/wheel.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/__pycache__/metadata_legacy.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/__pycache__/wheel_editable.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/__pycache__/metadata.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/__pycache__/build_tracker.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/__pycache__/metadata_editable.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/operations/build/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/req/__pycache__/constructors.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/req/__pycache__/req_install.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/req/__pycache__/req_dependency_group.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/req/__pycache__/req_set.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/req/__pycache__/req_uninstall.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/req/__pycache__/req_file.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/req/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/resolution/legacy/__pycache__/resolver.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/resolution/legacy/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/resolution/__pycache__/base.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/resolution/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/__pycache__/resolver.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/__pycache__/reporter.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/__pycache__/requirements.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/__pycache__/base.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/__pycache__/candidates.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/__pycache__/provider.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/__pycache__/factory.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/__pycache__/found_candidates.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/vcs/__pycache__/versioncontrol.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/vcs/__pycache__/bazaar.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/vcs/__pycache__/subversion.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/vcs/__pycache__/git.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/vcs/__pycache__/mercurial.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/vcs/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/locations/_distutils.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/locations/__pycache__/_distutils.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/locations/__pycache__/base.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/locations/__pycache__/_sysconfig.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/locations/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/index/__pycache__/sources.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/index/__pycache__/collector.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/index/__pycache__/package_finder.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/index/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/search.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/check.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/show.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/list.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/download.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/freeze.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/hash.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/debug.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/wheel.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/cache.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/help.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/install.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/configuration.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/uninstall.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/completion.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/index.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/lock.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/commands/__pycache__/inspect.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/metadata/__pycache__/base.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/metadata/__pycache__/pkg_resources.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/metadata/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/metadata/__pycache__/_json.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/metadata/importlib/_dists.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/metadata/importlib/__pycache__/_compat.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/metadata/importlib/__pycache__/_dists.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/metadata/importlib/__pycache__/_envs.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/metadata/importlib/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/distributions/__init__.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/distributions/sdist.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/distributions/installed.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/distributions/base.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/distributions/wheel.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/distributions/__pycache__/base.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/distributions/__pycache__/installed.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/distributions/__pycache__/wheel.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/distributions/__pycache__/sdist.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_internal/distributions/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/licenses/__pycache__/_spdx.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/licenses/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/__pycache__/markers.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/__pycache__/requirements.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/__pycache__/_musllinux.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/__pycache__/utils.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/__pycache__/tags.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/__pycache__/metadata.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/__pycache__/_tokenizer.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/__pycache__/_manylinux.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/__pycache__/_structures.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/__pycache__/specifiers.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/__pycache__/version.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/__pycache__/_elffile.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/packaging/__pycache__/_parser.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/truststore/__pycache__/_windows.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/truststore/__pycache__/_api.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/truststore/__pycache__/_macos.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/truststore/__pycache__/_openssl.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/truststore/__pycache__/_ssl_constants.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/truststore/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/msgpack/__pycache__/fallback.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/msgpack/__pycache__/exceptions.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/msgpack/__pycache__/ext.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/msgpack/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/dependency_groups/__pycache__/_implementation.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/dependency_groups/__pycache__/_toml_compat.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/dependency_groups/__pycache__/_pip_wrapper.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/dependency_groups/__pycache__/_lint_dependency_groups.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/dependency_groups/__pycache__/__main__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/dependency_groups/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/filters/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/lexers/__pycache__/_mapping.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/lexers/__pycache__/python.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/lexers/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/formatters/__pycache__/_mapping.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/formatters/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/__pycache__/formatter.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/__pycache__/regexopt.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/__pycache__/scanner.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/__pycache__/lexer.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/__pycache__/plugin.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/__pycache__/style.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/__pycache__/token.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/__pycache__/unistring.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/__pycache__/modeline.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/__pycache__/util.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/__pycache__/sphinxext.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/__pycache__/filter.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/__pycache__/__main__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/__pycache__/console.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/styles/__pycache__/_mapping.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pygments/styles/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/w64-arm.exe'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/w32.exe'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/locators.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/metadata.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/version.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/compat.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/index.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/manifest.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/util.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/database.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/t32.exe'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/__init__.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/w64.exe'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/markers.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/resources.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/t64-arm.exe'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/scripts.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/t64.exe'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/wheel.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/__pycache__/markers.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/__pycache__/compat.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/__pycache__/resources.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/__pycache__/scripts.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/__pycache__/wheel.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/__pycache__/metadata.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/__pycache__/locators.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/__pycache__/util.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/__pycache__/index.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/__pycache__/version.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/__pycache__/database.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distlib/__pycache__/manifest.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distro/__init__.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distro/py.typed'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distro/distro.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distro/__main__.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distro/__pycache__/distro.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distro/__pycache__/__main__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/distro/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/cachecontrol/__pycache__/serialize.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/cachecontrol/__pycache__/controller.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/cachecontrol/__pycache__/filewrapper.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/cachecontrol/__pycache__/_cmd.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/cachecontrol/__pycache__/cache.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/cachecontrol/__pycache__/adapter.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/cachecontrol/__pycache__/wrapper.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/cachecontrol/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/cachecontrol/__pycache__/heuristics.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/cachecontrol/caches/__pycache__/file_cache.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/cachecontrol/caches/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/cachecontrol/caches/__pycache__/redis_cache.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/idna/idnadata.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/idna/uts46data.py'  # Generated file pattern
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/idna/__pycache__/codec.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/idna/__pycache__/core.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/idna/__pycache__/idnadata.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/idna/__pycache__/compat.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/idna/__pycache__/package_data.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/idna/__pycache__/uts46data.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/idna/__pycache__/intranges.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/idna/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/__pycache__/typing_extensions.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/__version__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/api.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/adapters.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/_internal_utils.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/compat.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/sessions.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/hooks.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/utils.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/status_codes.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/cookies.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/exceptions.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/models.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/help.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/packages.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/auth.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/certs.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/requests/__pycache__/structures.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/tomli/__pycache__/_types.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/tomli/__pycache__/_re.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/tomli/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/tomli/__pycache__/_parser.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/certifi/__pycache__/core.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/certifi/__pycache__/__main__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/certifi/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/__pycache__/_impl.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/__pycache__/_in_process.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/highlighter.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_emoji_replace.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/segment.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/color.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/theme.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_windows.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/constrain.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/rule.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/containers.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/cells.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/ansi.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/file_proxy.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_ratio.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/layout.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_emoji_codes.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/scope.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/abc.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/pretty.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_loop.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/logging.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_cell_widths.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/terminal_theme.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_palettes.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/style.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_log_render.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/filesize.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/live_render.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/text.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_fileno.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/prompt.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/progress.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/errors.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/bar.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_spinners.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/default_styles.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/status.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/repr.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/tree.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_extension.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/measure.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/screen.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/palette.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/region.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/themes.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/emoji.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_stack.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/control.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_inspect.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/syntax.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/panel.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/table.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_wrap.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/live.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/align.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/jupyter.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/markup.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_windows_renderer.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/protocol.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_pick.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_timer.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/spinner.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/styled.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/json.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_export_format.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/pager.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/progress_bar.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/__main__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/box.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/columns.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/diagnose.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/traceback.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_null_file.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/_win32_console.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/console.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/color_triplet.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/rich/__pycache__/padding.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/tomli_w/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/tomli_w/__pycache__/_writer.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/util/__pycache__/wait.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/util/__pycache__/ssltransport.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/util/__pycache__/queue.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/util/__pycache__/ssl_match_hostname.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/util/__pycache__/response.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/util/__pycache__/timeout.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/util/__pycache__/proxy.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/util/__pycache__/connection.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/util/__pycache__/ssl_.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/util/__pycache__/request.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/util/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/util/__pycache__/retry.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/util/__pycache__/url.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/__pycache__/poolmanager.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/__pycache__/connectionpool.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/__pycache__/fields.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/__pycache__/filepost.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/__pycache__/response.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/__pycache__/exceptions.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/__pycache__/_version.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/__pycache__/connection.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/__pycache__/request.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/__pycache__/_collections.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/contrib/__pycache__/securetransport.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/contrib/__pycache__/pyopenssl.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/contrib/__pycache__/appengine.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/contrib/__pycache__/ntlmpool.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/contrib/__pycache__/socks.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/contrib/__pycache__/_appengine_environ.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/contrib/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/contrib/_securetransport/__pycache__/bindings.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/contrib/_securetransport/__pycache__/low_level.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/contrib/_securetransport/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/packages/__pycache__/six.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/packages/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/packages/backports/__pycache__/weakref_finalize.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/packages/backports/__pycache__/makefile.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/urllib3/packages/backports/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/pkg_resources/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/resolvelib/__pycache__/reporters.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/resolvelib/__pycache__/providers.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/resolvelib/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/resolvelib/__pycache__/structs.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/resolvelib/resolvers/__pycache__/exceptions.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/resolvelib/resolvers/__pycache__/criterion.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/resolvelib/resolvers/__pycache__/abstract.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/resolvelib/resolvers/__pycache__/resolution.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/resolvelib/resolvers/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/platformdirs/__pycache__/api.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/platformdirs/__pycache__/android.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/platformdirs/__pycache__/windows.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/platformdirs/__pycache__/macos.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/platformdirs/__pycache__/__main__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/platformdirs/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/platformdirs/__pycache__/version.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/_vendor/platformdirs/__pycache__/unix.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/__pycache__/__pip-runner__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/__pycache__/__main__.cpython-313.pyc'  # Python cache file
# rm -rf 'venv/lib/python3.13/site-packages/pip/__pycache__/__init__.cpython-313.pyc'  # Python cache file
# rm -rf 'src/deployment/distributed.py'  # Generated file pattern

# OBSOLETE FILES (Review before uncommenting)
echo 'Would clean obsolete files (currently commented out)...'
# rm 'comprehensive_system_test.py'  # Not imported, not recently modified
# rm 'tests/conftest.py'  # Not imported, not recently modified
# rm 'tests/comprehensive_validation_suite.py'  # Not imported, not recently modified
# rm 'tests/test_bayesian_rl_suite.py'  # Not imported, not recently modified
# rm 'tests/__init__.py'  # Not imported, not recently modified
# rm 'tests/mathematical_validation_suite.py'  # Not imported, not recently modified
# rm 'tests/test_safe_rl_system.py'  # Not imported, not recently modified
# rm 'tests/comprehensive_test_suite.py'  # Not imported, not recently modified
# rm 'tests/unit/test_human_behavior.py'  # Not imported, not recently modified
# rm 'tests/unit/test_feature_extraction.py'  # Not imported, not recently modified
# rm 'tests/unit/test_gaussian_process.py'  # Not imported, not recently modified
# rm 'tests/unit/test_visualization_suite.py'  # Not imported, not recently modified
# rm 'tests/unit/test_logger.py'  # Not imported, not recently modified
# rm 'tests/unit/test_synthetic_generator.py'  # Not imported, not recently modified
# rm 'tests/unit/control/test_robot_dynamics.py'  # Not imported, not recently modified
# rm 'tests/unit/control/__init__.py'  # Not imported, not recently modified
# rm 'tests/unit/control/test_mpc_controller.py'  # Not imported, not recently modified
# rm 'tests/integration/test_complete_pipeline.py'  # Not imported, not recently modified
# rm 'tests/integration/__init__.py'  # Not imported, not recently modified
# rm 'tests/integration/test_performance_integration.py'  # Not imported, not recently modified

echo 'Cleanup complete!'
echo 'REMEMBER: Review this script before executing!'
